### ISSUE TITLE
Resizeable disk grows Win10 boot partition

### ISSUE THREAD

**Issue by MilanKerslager** [FOGProject/fog-too#10]
I tried to use resizeable image with W10 & Linux.
It worked fine, but the very first partition for booting Windows 10 was grown from 500MB to over 700MB (on a bigger disc). 
The first partition has NTFS filesystem and I think should not grow.

**Comment by MilanKerslager** [comment]
I have latest trunk installed (2015-09-18).

**Comment by schmittjoseph** [comment]
This repository is for our rewrite of FOG. Please post this issue here instead https://github.com/FOGProject/fogproject
