### ISSUE TITLE
Unable to set password in Storage managment

### ISSUE THREAD

**Issue by MilanKerslager** [FOGProject/fog-too#9]
I was uploading my first image and after Partclone was done I have got an error mesage on the screen about bad FTp password when connecting to the client.
I tryed to change password at Storage managment (I have only one node with Fog web UI), but this password could not be changed.
The password could be changed at global FOG configuration - FOG Settings (FOG_TFTP_FTP_PASSWORD).
I saw similar error message with no answer at https://forums.fogproject.org/topic/4203/fog-ftp-password

**Comment by MilanKerslager** [comment]
I have latest trunk installed (2015-09-18).

**Comment by schmittjoseph** [comment]
This repository is for our rewrite of FOG. Please post this issue here instead https://github.com/FOGProject/fogproject
